#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WWW-Extractor
version:      0.4
version_from: lib/WWW/Extractor.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.13
